//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails_1
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string Address { get; set; }
        public string HaveAlliance { get; set; }
        public string HavePrescriptions { get; set; }
    }
}
